### ISSUE TITLE
Configure database

### ISSUE THREAD

**Issue by pirvudoru** [code4romania/teacher-workout-backend#3]
We will use PostgreSQL. Configure EntityFramework to use PostgreSQL.
We need a way to configure the env (consider .env or similar).

- Add an example of the config
- Update Readme to reference the example config.

**Comment by levelboy** [comment]
I can take this

**Comment by levelboy** [comment]
The .env setup is already done here:https://github.com/code4romania/teacher-workout-backend/commit/097e5f4286f379d21d0233356f5002f3e9794f75

I'll handle the Entity Framework setup with the PostgreSQL db.

**Comment by levelboy** [comment]
Closing this. Alina will add the changes
