### ISSUE TITLE
Add support for tests

### ISSUE THREAD

**Issue by pirvudoru** [code4romania/teacher-workout-backend#7]
We need a project where we can write tests against the API.

We need to support:
- unit tests
- integration tests

**Comment by iustinnicu** [comment]
I've started to derive an initial checklist to check against for the UX based on the [Figma document](https://www.figma.com/file/uLiqrlxmOB5xCppIzmiUXV/Teacher-Workout?node-id=0%3A1).

For the functionalities I will derive the usecases list from [backend repository WIKI](https://github.com/code4romania/teacher-workout-backend/wiki) initially as a checklist.

Later I will try to automate the functional tests using. [Appium](https://appium.io/)

@catileptic @AlexandraDamaschin

**Comment by pirvudoru** [comment]
Taking this.
